[build.environment]
  NPM_FLAGS="--version"

[build]
  command = "npx pnpm i --store=node_modules/.pnpm-store --frozen-lockfile && npx pnpm run build"
  publish = "dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    cache-control = "public, max-age=2592000"